# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user1 = User.create(name:"Beau",user_type:"Admin")
user2 = User.create(name:"Anuj",user_type:"Admin")
user3 = User.create(name:"Joe",user_type:"Admin")
user4 = User.create(name:"Rachel",user_type:"Admin")
user5 = User.create(name:"Mandy",user_type:"Admin")
user6 = User.create(name:"Shinik",user_type:"Admin")
user7 = User.create(name:"Ben",user_type:"Admin")
user8 = User.create(name:"Ash",user_type:"Admin")
user9 = User.create(name:"JC",user_type:"Admin")
user10 = User.create(name:"Vlad",user_type:"Admin")
user11 = User.create(name:"Kiley",user_type:"Admin")
user12 = User.create(name:"Robin",user_type:"Admin")
user13 = User.create(name:"Jonnel",user_type:"Admin")
user14 = User.create(name:"Will",user_type:"Admin")
user15 = User.create(name:"Bruno",user_type:"Admin")
user16 = User.create(name:"Ann",user_type:"Admin")
user17 = User.create(name:"Paul",user_type:"Admin")

#usergames

song1 = Song.create(artist:"Queen", title:"Bohemian Rhapsody", filename:"queen-bohemian-rhapsody")
song2 = Song.create(artist:"Aerosmith", title:"Cryin", filename:"Aerosmith-cryin")
song3 = Song.create(artist:"Neil Diamond", title:"Sweet Caroline", filename:"Neil-Diamond-Sweet-Caroline")
song4 = Song.create(artist:"Destiny's Child", title:"Say My Name", filename:"Destiny's-Child-Say-My-Name")
song5 = Song.create(artist:"The B-52's", title:"Love Shack", filename:"The-B-52's-Love-shack")
song6 = Song.create(artist:"Hall & Oates", title:"Rich Girl", filename:"hall&Oates-rich-girl")
song7 = Song.create(artist:"Cyndi Lauper", title:"Girls Just Want To Have Fun", filename:"cyndi-lauper-girls-just-want-to-have-fun")
song8 = Song.create(artist:"Shania Twain", title:"Man! I Feel Like A Woman", filename:"shania-twain-man-i-feel-like-a-woman")
song9 = Song.create(artist:"Journey", title:"Don't Stop Believin", filename:"journey-don't-stop-believin")
song10 = Song.create(artist:"The Human League", title:"Don't You Want Me", filename:"the-human-league-don't-you-want-me")
song11 = Song.create(artist:"Lynyrd Skynyrd", title:"Sweet Home Alabama", filename:"lynyrd-skynyrd-sweet-home-alabama")
song12 = Song.create(artist:"Olivia Newton John", title:"Summer Nights", filename:"olivia-newton-john-summer-nights")
song13 = Song.create(artist:"Whitney Houston", title:"I Wanna Dance With Somebody", filename:"whitney-houston-i-wanna-dance-with-somebody")
song14 = Song.create(artist:"Johnny Cash", title:"Ring Of Fire", filename:"johnny-cash-ring-of-fire")
song15 = Song.create(artist:"Abba", title:"Dancing Queen", filename:"abba-dancing-queen")
song16 = Song.create(artist:"Prince", title:"Purple Rain", filename:"prince-purple-rain")
song17 = Song.create(artist:"Madonna", title:"Like A Prayer", filename:"madonna-like-a-prayer")
song18 = Song.create(artist:"Marvin Gaye", title:"Let's Get It On", filename:"marvin-gaye-let's-get-it-on")
song19 = Song.create(artist:"Hall & Oates", title:"Private Eyes", filename:"hall&oates-private-eyes")
song20 = Song.create(artist:"Backstreet Boys", title:"I Want It That Way", filename:"backstreet-boys-i-want-it-that-way")



queued_song1 = SelectedSong.create(song_id:1, user_id:1, played:true)
queued_song2 = SelectedSong.create(song_id:2, user_id:2, played:false)
queued_song3 = SelectedSong.create(song_id:3, user_id:3, played:true)
queued_song4 = SelectedSong.create(song_id:4, user_id:4, played:true)
queued_song5 = SelectedSong.create(song_id:5, user_id:5, played:false)
queued_song6 = SelectedSong.create(song_id:6, user_id:1, played:true)
queued_song7 = SelectedSong.create(song_id:7, user_id:2, played:true)
queued_song8 = SelectedSong.create(song_id:8, user_id:3, played:true)
queued_song9 = SelectedSong.create(song_id:9, user_id:4, played:true)
queued_song10 = SelectedSong.create(song_id:10, user_id:5, played:false)
queued_song11 = SelectedSong.create(song_id:1, user_id:2, played:true)
queued_song12 = SelectedSong.create(song_id:2, user_id:3, played:true)
queued_song13 = SelectedSong.create(song_id:3, user_id:4, played:true)
queued_song14 = SelectedSong.create(song_id:4, user_id:5, played:false)
queued_song15 = SelectedSong.create(song_id:5, user_id:1, played:true)
queued_song16 = SelectedSong.create(song_id:6, user_id:1, played:true)
queued_song17 = SelectedSong.create(song_id:7, user_id:1, played:false)
queued_song18 = SelectedSong.create(song_id:8, user_id:1, played:true)
queued_song19 = SelectedSong.create(song_id:9, user_id:1, played:true)
queued_song20 = SelectedSong.create(song_id:10, user_id:1, played:true)
